### ISSUE TITLE
Run arguments are quoted the wrong way

### ISSUE THREAD

**Issue by alexvetter** [aesteve/gradle-redeploy#1]
Hi Arnaud,

I tried to implement the gradle redeploy on my scala-based vert-x3 application but I failed with your configuration. I played around with the quotes on the run arguments and in the end the following worked for me:

``` groovy
mainClassName = "io.vertx.core.Launcher"
def mainVerticle = "com.campudus.tableaux.Starter"

run {
    args = [
            "run",
            mainVerticle,
            "-conf", "conf.json",
            "--redeploy=src/main/**/*.scala",
            "--launcher-class=${mainClassName}",
            "--on-redeploy=./gradlew shadowJar"
    ]
}
```

So the `launcher-class` needs to be the new Launcher instead of the main verticle and the quotes on the arguments (even with spaces) aren't needed. In fact they prevent it from working. Also it needs to be `--on-redeploy` instead of `-on-redeploy`.

I'm curious did your configuration work for you?

**Comment by aesteve** [comment]
Hi !

No it didn't work at all, I was about to ask Clément if he had any insight to give me.

Glad you got something working ! I'll try it home this evening.

You can show Clément your working example here : https://github.com/eclipse/vert.x/issues/1253#issuecomment-166547302

I'm sure he'll be happy to add it to the Vert.x official documentation (or maybe you could submit an example as a PR in the vertx-examples project directly ? I'm sure it'd be much appreciated).

Thanks for the help !

**Comment by aesteve** [comment]
Also, I'm currently learning Scala on my free time, and I'd be really happy to see what an app built with Scala + Vert.x 3 looks like. I think it'd help me to see how people are using Scala together with APIs I already know.

If you have any pointer (maybe not your project directly, but at this point I take anythings), thanks :)

**Comment by alexvetter** [comment]
So, I think I will add a gradle redeploy example to vertx-examples. I hope it's not to complicated to contribute to a eclipse project.
AFAIK, there is currently only our project (tableaux) which was ported from vertx 2 to vert-x3.

**Comment by aesteve** [comment]
Thanks a lot !

**Comment by alexvetter** [comment]
fyi https://github.com/vert-x3/vertx-examples/pull/113
